<?php

namespace Database\Seeders;

use App\Models\Recipe;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    public function run(): void
    {
        if (Recipe::count() > 0) {
            return;
        }

        $recipes = [
            [
                'name'         => 'High-Protein Chicken Rice Bowl',
                'description'  => 'A balanced post-workout meal with lean protein, complex carbs, and vibrant veggies.',
                'image_url'    => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop',
                'category'     => 'Lunch',
                'tags'         => ['High Protein', 'Meal Prep'],
                'prep_time'    => 15,
                'cook_time'    => 25,
                'servings'     => 2,
                'calories'     => 485,
                'protein'      => 52,
                'carbs'        => 38,
                'fat'          => 12,
                'fiber'        => 6,
                'rating'       => null,
                'reviews_count' => 0,
                'ingredients'  => [
                    ['name' => 'Chicken breast', 'amount' => '200', 'unit' => 'g'],
                    ['name' => 'Brown rice', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Broccoli', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Bell pepper', 'amount' => '1', 'unit' => 'medium'],
                    ['name' => 'Soy sauce', 'amount' => '2', 'unit' => 'tbsp'],
                    ['name' => 'Olive oil', 'amount' => '1', 'unit' => 'tbsp'],
                ],
                'instructions' => [
                    'Cook brown rice according to package directions.',
                    'Season chicken breast with salt, pepper, and garlic powder.',
                    'Grill or pan-fry chicken 6-7 minutes per side until cooked through.',
                    'Stir-fry broccoli and bell pepper in olive oil for 5 minutes.',
                    'Slice chicken and serve over rice with vegetables and soy sauce.',
                ],
            ],
            [
                'name'         => 'Greek Yogurt Protein Parfait',
                'description'  => 'A quick, no-cook breakfast packed with protein and probiotics to fuel your morning.',
                'image_url'    => 'https://images.unsplash.com/photo-1557844352-761f2565b576?w=600&h=400&fit=crop',
                'category'     => 'Breakfast',
                'tags'         => ['Quick', 'Meal Prep', 'Vegetarian'],
                'prep_time'    => 5,
                'cook_time'    => 0,
                'servings'     => 1,
                'calories'     => 412,
                'protein'      => 35,
                'carbs'        => 48,
                'fat'          => 9,
                'fiber'        => 8,
                'rating'       => null,
                'reviews_count' => 0,
                'ingredients'  => [
                    ['name' => 'Greek yogurt (0% fat)', 'amount' => '200', 'unit' => 'g'],
                    ['name' => 'Granola', 'amount' => '1/3', 'unit' => 'cup'],
                    ['name' => 'Mixed berries', 'amount' => '1/2', 'unit' => 'cup'],
                    ['name' => 'Honey', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Chia seeds', 'amount' => '1', 'unit' => 'tbsp'],
                ],
                'instructions' => [
                    'Layer half the yogurt in a bowl or jar.',
                    'Add half the granola and berries.',
                    'Repeat layers.',
                    'Drizzle with honey and sprinkle chia seeds on top.',
                    'Serve immediately or refrigerate overnight.',
                ],
            ],
            [
                'name'         => 'Salmon with Roasted Asparagus',
                'description'  => 'Omega-3 rich salmon paired with crispy roasted asparagus for a nutrient-dense dinner.',
                'image_url'    => 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&h=400&fit=crop',
                'category'     => 'Dinner',
                'tags'         => ['High Protein', 'Low Carb'],
                'prep_time'    => 10,
                'cook_time'    => 20,
                'servings'     => 2,
                'calories'     => 520,
                'protein'      => 48,
                'carbs'        => 12,
                'fat'          => 28,
                'fiber'        => 4,
                'rating'       => null,
                'reviews_count' => 0,
                'ingredients'  => [
                    ['name' => 'Salmon fillet', 'amount' => '250', 'unit' => 'g'],
                    ['name' => 'Asparagus', 'amount' => '200', 'unit' => 'g'],
                    ['name' => 'Lemon', 'amount' => '1', 'unit' => 'whole'],
                    ['name' => 'Garlic', 'amount' => '3', 'unit' => 'cloves'],
                    ['name' => 'Olive oil', 'amount' => '2', 'unit' => 'tbsp'],
                    ['name' => 'Fresh dill', 'amount' => '2', 'unit' => 'tbsp'],
                ],
                'instructions' => [
                    'Preheat oven to 200°C (400°F).',
                    'Toss asparagus with 1 tbsp olive oil, salt, and garlic. Spread on a baking sheet.',
                    'Place salmon on the same sheet. Drizzle with remaining oil and lemon juice.',
                    'Season with salt, pepper, and dill.',
                    'Roast 15-18 minutes until salmon flakes easily. Serve with lemon wedges.',
                ],
            ],
            [
                'name'         => 'Turkey Zucchini Stir-Fry',
                'description'  => 'Lightning-fast lean turkey stir-fry with zucchini noodles — low carb and filling.',
                'image_url'    => 'https://images.unsplash.com/photo-1613514785940-daed07799d9b?w=600&h=400&fit=crop',
                'category'     => 'Dinner',
                'tags'         => ['High Protein', 'Low Carb', 'Quick'],
                'prep_time'    => 10,
                'cook_time'    => 15,
                'servings'     => 2,
                'calories'     => 365,
                'protein'      => 42,
                'carbs'        => 18,
                'fat'          => 11,
                'fiber'        => 5,
                'rating'       => null,
                'reviews_count' => 0,
                'ingredients'  => [
                    ['name' => 'Ground turkey', 'amount' => '300', 'unit' => 'g'],
                    ['name' => 'Zucchini', 'amount' => '2', 'unit' => 'large'],
                    ['name' => 'Onion', 'amount' => '1', 'unit' => 'medium'],
                    ['name' => 'Garlic', 'amount' => '4', 'unit' => 'cloves'],
                    ['name' => 'Soy sauce', 'amount' => '3', 'unit' => 'tbsp'],
                    ['name' => 'Sesame oil', 'amount' => '1', 'unit' => 'tsp'],
                ],
                'instructions' => [
                    'Spiralize zucchini into noodles or use a peeler for ribbons.',
                    'Brown ground turkey in a hot skillet, breaking it up.',
                    'Add onion and garlic, cook 2-3 minutes.',
                    'Add zucchini noodles, soy sauce, and sesame oil.',
                    'Toss for 2-3 minutes until just tender. Serve immediately.',
                ],
            ],
            [
                'name'         => 'Avocado Toast with Poached Eggs',
                'description'  => 'The classic high-protein breakfast elevated with perfect poached eggs and everything bagel seasoning.',
                'image_url'    => 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&h=400&fit=crop',
                'category'     => 'Breakfast',
                'tags'         => ['Quick', 'Vegetarian', 'High Protein'],
                'prep_time'    => 5,
                'cook_time'    => 10,
                'servings'     => 1,
                'calories'     => 420,
                'protein'      => 18,
                'carbs'        => 32,
                'fat'          => 24,
                'fiber'        => 9,
                'rating'       => null,
                'reviews_count' => 0,
                'ingredients'  => [
                    ['name' => 'Whole grain bread', 'amount' => '2', 'unit' => 'slices'],
                    ['name' => 'Avocado', 'amount' => '1', 'unit' => 'whole'],
                    ['name' => 'Eggs', 'amount' => '2', 'unit' => 'large'],
                    ['name' => 'Lemon juice', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Red pepper flakes', 'amount' => '1/4', 'unit' => 'tsp'],
                    ['name' => 'Everything bagel seasoning', 'amount' => '1', 'unit' => 'tsp'],
                ],
                'instructions' => [
                    'Toast bread until golden brown.',
                    'Mash avocado with lemon juice, salt, and pepper.',
                    'Bring a pot of water to a gentle simmer. Add a splash of vinegar.',
                    'Crack eggs into simmering water, poach 3-4 minutes.',
                    'Spread avocado on toast, top with poached eggs, seasoning, and pepper flakes.',
                ],
            ],
            [
                'name'         => 'Green Power Smoothie',
                'description'  => 'A nutrient-dense smoothie packed with spinach, banana, and protein powder for sustained energy.',
                'image_url'    => 'https://images.unsplash.com/photo-1553530666-ba11a90a0edc?w=600&h=400&fit=crop',
                'category'     => 'Smoothies',
                'tags'         => ['Quick', 'High Protein', 'Vegetarian'],
                'prep_time'    => 5,
                'cook_time'    => 0,
                'servings'     => 1,
                'calories'     => 310,
                'protein'      => 28,
                'carbs'        => 42,
                'fat'          => 5,
                'fiber'        => 7,
                'rating'       => null,
                'reviews_count' => 0,
                'ingredients'  => [
                    ['name' => 'Baby spinach', 'amount' => '2', 'unit' => 'cups'],
                    ['name' => 'Frozen banana', 'amount' => '1', 'unit' => 'large'],
                    ['name' => 'Vanilla protein powder', 'amount' => '1', 'unit' => 'scoop'],
                    ['name' => 'Almond milk', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Chia seeds', 'amount' => '1', 'unit' => 'tbsp'],
                    ['name' => 'Honey', 'amount' => '1', 'unit' => 'tsp'],
                ],
                'instructions' => [
                    'Add almond milk and spinach to blender first.',
                    'Add frozen banana, protein powder, and chia seeds.',
                    'Blend on high for 60 seconds until completely smooth.',
                    'Taste and add honey if desired.',
                    'Pour into a chilled glass and serve immediately.',
                ],
            ],
            [
                'name'         => 'Tuna Salad Lettuce Wraps',
                'description'  => 'Crisp lettuce cups filled with protein-packed tuna salad — ready in minutes, zero carbs.',
                'image_url'    => 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&h=400&fit=crop',
                'category'     => 'Lunch',
                'tags'         => ['Quick', 'Low Carb', 'High Protein'],
                'prep_time'    => 10,
                'cook_time'    => 0,
                'servings'     => 2,
                'calories'     => 240,
                'protein'      => 36,
                'carbs'        => 8,
                'fat'          => 8,
                'fiber'        => 3,
                'rating'       => null,
                'reviews_count' => 0,
                'ingredients'  => [
                    ['name' => 'Canned tuna in water', 'amount' => '2', 'unit' => 'cans (142g each)'],
                    ['name' => 'Greek yogurt', 'amount' => '3', 'unit' => 'tbsp'],
                    ['name' => 'Dijon mustard', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Celery', 'amount' => '2', 'unit' => 'stalks'],
                    ['name' => 'Red onion', 'amount' => '2', 'unit' => 'tbsp'],
                    ['name' => 'Butter lettuce leaves', 'amount' => '8', 'unit' => 'leaves'],
                ],
                'instructions' => [
                    'Drain tuna thoroughly and flake into a bowl.',
                    'Mix in Greek yogurt, Dijon mustard, salt, and pepper.',
                    'Finely dice celery and red onion, stir into tuna.',
                    'Wash and dry lettuce leaves.',
                    'Spoon tuna mixture into lettuce cups. Serve chilled.',
                ],
            ],
            [
                'name'         => 'Overnight Oats with Protein',
                'description'  => 'Prep the night before and wake up to a ready-to-eat, protein-rich breakfast all week.',
                'image_url'    => 'https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?w=600&h=400&fit=crop',
                'category'     => 'Breakfast',
                'tags'         => ['Meal Prep', 'High Protein', 'Vegetarian'],
                'prep_time'    => 5,
                'cook_time'    => 0,
                'servings'     => 1,
                'calories'     => 445,
                'protein'      => 32,
                'carbs'        => 58,
                'fat'          => 10,
                'fiber'        => 9,
                'rating'       => null,
                'reviews_count' => 0,
                'ingredients'  => [
                    ['name' => 'Rolled oats', 'amount' => '1/2', 'unit' => 'cup'],
                    ['name' => 'Chocolate protein powder', 'amount' => '1', 'unit' => 'scoop'],
                    ['name' => 'Almond milk', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Greek yogurt', 'amount' => '100', 'unit' => 'g'],
                    ['name' => 'Banana', 'amount' => '1/2', 'unit' => 'medium'],
                    ['name' => 'Cocoa powder', 'amount' => '1', 'unit' => 'tsp'],
                ],
                'instructions' => [
                    'Combine oats, protein powder, and cocoa powder in a jar.',
                    'Add Greek yogurt and almond milk. Stir well.',
                    'Slice banana and place on top.',
                    'Cover and refrigerate overnight (minimum 6 hours).',
                    'Grab and go in the morning. Add toppings of your choice.',
                ],
            ],
            [
                'name'         => 'Sweet Potato & Black Bean Bowl',
                'description'  => 'A hearty plant-based bowl with roasted sweet potato, black beans, and avocado crema.',
                'image_url'    => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop',
                'category'     => 'Dinner',
                'tags'         => ['Vegetarian', 'Meal Prep', 'High Protein'],
                'prep_time'    => 15,
                'cook_time'    => 30,
                'servings'     => 2,
                'calories'     => 480,
                'protein'      => 18,
                'carbs'        => 72,
                'fat'          => 14,
                'fiber'        => 16,
                'rating'       => null,
                'reviews_count' => 0,
                'ingredients'  => [
                    ['name' => 'Sweet potato', 'amount' => '2', 'unit' => 'medium'],
                    ['name' => 'Black beans (canned)', 'amount' => '1', 'unit' => 'can (400g)'],
                    ['name' => 'Avocado', 'amount' => '1', 'unit' => 'whole'],
                    ['name' => 'Lime', 'amount' => '1', 'unit' => 'whole'],
                    ['name' => 'Cumin', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Chili powder', 'amount' => '1/2', 'unit' => 'tsp'],
                ],
                'instructions' => [
                    'Preheat oven to 200°C. Cube sweet potato, toss with oil, cumin, and chili powder.',
                    'Roast sweet potato 25-30 minutes until caramelized.',
                    'Heat drained black beans with salt and cumin in a pan.',
                    'Blend avocado with lime juice and salt for the crema.',
                    'Layer sweet potato and beans in bowls, top with avocado crema.',
                ],
            ],
            [
                'name'         => 'Protein Banana Pancakes',
                'description'  => 'Two-ingredient base pancakes with added protein powder — fluffy, sweet, and macro-friendly.',
                'image_url'    => 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&h=400&fit=crop',
                'category'     => 'Breakfast',
                'tags'         => ['High Protein', 'Quick', 'Vegetarian'],
                'prep_time'    => 5,
                'cook_time'    => 10,
                'servings'     => 1,
                'calories'     => 380,
                'protein'      => 30,
                'carbs'        => 46,
                'fat'          => 8,
                'fiber'        => 4,
                'rating'       => null,
                'reviews_count' => 0,
                'ingredients'  => [
                    ['name' => 'Ripe banana', 'amount' => '2', 'unit' => 'medium'],
                    ['name' => 'Eggs', 'amount' => '2', 'unit' => 'large'],
                    ['name' => 'Vanilla protein powder', 'amount' => '1', 'unit' => 'scoop'],
                    ['name' => 'Cinnamon', 'amount' => '1/2', 'unit' => 'tsp'],
                    ['name' => 'Coconut oil', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Fresh berries', 'amount' => '1/2', 'unit' => 'cup'],
                ],
                'instructions' => [
                    'Mash bananas until smooth in a bowl.',
                    'Whisk in eggs, protein powder, and cinnamon.',
                    'Heat coconut oil in a non-stick pan over medium-low heat.',
                    'Pour small rounds (2-3 tbsp each) and cook 2 minutes per side.',
                    'Serve with fresh berries and a drizzle of honey.',
                ],
            ],
            [
                'name'         => 'Shrimp & Veggie Stir-Fry',
                'description'  => 'Quick and colorful shrimp stir-fry with a savory garlic-ginger sauce over cauliflower rice.',
                'image_url'    => 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=600&h=400&fit=crop',
                'category'     => 'Dinner',
                'tags'         => ['Quick', 'High Protein', 'Low Carb'],
                'prep_time'    => 10,
                'cook_time'    => 12,
                'servings'     => 2,
                'calories'     => 320,
                'protein'      => 38,
                'carbs'        => 22,
                'fat'          => 9,
                'fiber'        => 5,
                'rating'       => null,
                'reviews_count' => 0,
                'ingredients'  => [
                    ['name' => 'Large shrimp (peeled)', 'amount' => '300', 'unit' => 'g'],
                    ['name' => 'Cauliflower rice', 'amount' => '2', 'unit' => 'cups'],
                    ['name' => 'Snap peas', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Bell peppers', 'amount' => '2', 'unit' => 'medium'],
                    ['name' => 'Garlic', 'amount' => '4', 'unit' => 'cloves'],
                    ['name' => 'Fresh ginger', 'amount' => '1', 'unit' => 'inch piece'],
                    ['name' => 'Soy sauce', 'amount' => '3', 'unit' => 'tbsp'],
                ],
                'instructions' => [
                    'Season shrimp with salt and pepper.',
                    'Cook cauliflower rice in a dry pan 4-5 minutes. Set aside.',
                    'Stir-fry garlic and ginger in hot oil 30 seconds.',
                    'Add shrimp, cook 1-2 minutes per side until pink.',
                    'Add vegetables and soy sauce. Toss 3 minutes. Serve over cauliflower rice.',
                ],
            ],
            [
                'name'         => 'Trail Mix Energy Bites',
                'description'  => 'No-bake protein-packed bites made with oats, nut butter, and dark chocolate chips.',
                'image_url'    => 'https://images.unsplash.com/photo-1542691457-cbe4df041eb2?w=600&h=400&fit=crop',
                'category'     => 'Snacks',
                'tags'         => ['Meal Prep', 'High Protein', 'Vegetarian'],
                'prep_time'    => 15,
                'cook_time'    => 0,
                'servings'     => 12,
                'calories'     => 145,
                'protein'      => 6,
                'carbs'        => 18,
                'fat'          => 6,
                'fiber'        => 2,
                'rating'       => null,
                'reviews_count' => 0,
                'ingredients'  => [
                    ['name' => 'Rolled oats', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Peanut butter', 'amount' => '1/2', 'unit' => 'cup'],
                    ['name' => 'Honey', 'amount' => '1/3', 'unit' => 'cup'],
                    ['name' => 'Chocolate protein powder', 'amount' => '1', 'unit' => 'scoop'],
                    ['name' => 'Dark chocolate chips', 'amount' => '1/3', 'unit' => 'cup'],
                    ['name' => 'Flaxseed', 'amount' => '2', 'unit' => 'tbsp'],
                ],
                'instructions' => [
                    'Mix all ingredients in a large bowl until well combined.',
                    'Refrigerate the mixture for 30 minutes to firm up.',
                    'Roll into 1-inch balls using a tablespoon measure.',
                    'Place on a parchment-lined tray.',
                    'Refrigerate for at least 1 hour before eating. Store up to 1 week.',
                ],
            ],
        ];

        foreach ($recipes as $data) {
            // `status` is deliberately not fillable (see Recipe.php — only an
            // admin review may set it), so Recipe::create() alone left every
            // seeded row at the column default of `private`. The library query
            // is `where('status', 'approved')`, so a fresh `migrate --seed`
            // produced a Recipe Library reading "0 healthy recipes · No recipes
            // found" while all twelve sat invisible in the database.
            //
            // These twelve are the curated collection, authored by nobody
            // (`user_id` is null) — the same rows the review migration
            // explicitly approves. Say so here too, or the seeder and the
            // migration disagree about the starting state.
            Recipe::create($data)->forceFill([
                'status'    => Recipe::APPROVED,
                'is_public' => true,
            ])->save();
        }
    }
}
