<?php
namespace Database\Seeders;

use App\Models\Video;
use Illuminate\Database\Seeder;

class VideoSeeder extends Seeder
{
    public function run(): void
    {
        $videos = [
            [
                'title'            => 'Full Body HIIT Blast',
                'description'      => 'A high-intensity interval training session targeting every muscle group. Perfect for burning calories and improving cardiovascular fitness.',
                'video_url'        => 'https://www.youtube.com/embed/ml6cT4AZdqI',
                'thumbnail_url'    => 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=640&q=80',
                'duration_seconds' => 1800,
                'category'         => 'HIIT',
                'difficulty'       => 'Intermediate',
                'instructor'       => 'Coach Kelvin',
                'tags'             => ['cardio','full-body','fat-burn'],
                'muscle_groups'    => ['Full Body'],
                'equipment'        => ['None'],
                'views'            => 0,
                'likes'            => 0,
                'is_featured'      => true,
            ],
            [
                'title'            => 'Chest & Triceps Power',
                'description'      => 'Build a powerful upper body with this comprehensive chest and triceps workout using barbells and dumbbells.',
                'video_url'        => 'https://www.youtube.com/embed/vcBig73ojpE',
                'thumbnail_url'    => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=640&q=80',
                'duration_seconds' => 2700,
                'category'         => 'Strength',
                'difficulty'       => 'Intermediate',
                'instructor'       => 'Marcus Bell',
                'tags'             => ['chest','triceps','upper-body'],
                'muscle_groups'    => ['Chest','Triceps'],
                'equipment'        => ['Barbell','Dumbbell','Bench'],
                'views'            => 0,
                'likes'            => 0,
                'is_featured'      => false,
            ],
            [
                'title'            => 'Morning Yoga Flow',
                'description'      => 'Start your day with this calming yoga sequence designed to improve flexibility, reduce stress, and set a positive tone.',
                'video_url'        => 'https://www.youtube.com/embed/v7AYKMP6rOE',
                'thumbnail_url'    => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=640&q=80',
                'duration_seconds' => 1200,
                'category'         => 'Yoga',
                'difficulty'       => 'Beginner',
                'instructor'       => 'Sarah Chen',
                'tags'             => ['yoga','morning','flexibility','mindfulness'],
                'muscle_groups'    => ['Full Body','Core'],
                'equipment'        => ['Yoga Mat'],
                'views'            => 0,
                'likes'            => 0,
                'is_featured'      => true,
            ],
            [
                'title'            => 'Back & Biceps Hypertrophy',
                'description'      => 'Science-based workout for maximum muscle growth in the back and biceps. Includes pull-ups, rows, and curls.',
                'video_url'        => 'https://www.youtube.com/embed/FkFD3x3QSRQ',
                'thumbnail_url'    => 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=640&q=80',
                'duration_seconds' => 3300,
                'category'         => 'Strength',
                'difficulty'       => 'Advanced',
                'instructor'       => 'Marcus Bell',
                'tags'             => ['back','biceps','pull-day','hypertrophy'],
                'muscle_groups'    => ['Back','Biceps'],
                'equipment'        => ['Pull-up Bar','Barbell','Cable Machine'],
                'views'            => 0,
                'likes'            => 0,
                'is_featured'      => false,
            ],
            [
                'title'            => '5K Run Training Plan — Week 1',
                'description'      => 'Start your running journey with this beginner-friendly couch to 5K training session. Mix of walking and jogging intervals.',
                'video_url'        => 'https://www.youtube.com/embed/kVnyY17VS9Y',
                'thumbnail_url'    => 'https://images.unsplash.com/photo-1483721310020-03333e577078?w=640&q=80',
                'duration_seconds' => 2400,
                'category'         => 'Cardio',
                'difficulty'       => 'Beginner',
                'instructor'       => 'Coach Kelvin',
                'tags'             => ['running','cardio','beginner','5k'],
                'muscle_groups'    => ['Legs','Cardio'],
                'equipment'        => ['None'],
                'views'            => 0,
                'likes'            => 0,
                'is_featured'      => false,
            ],
            [
                'title'            => 'Core Strength & Stability',
                'description'      => 'Build a rock-solid core with this 20-minute routine. Planks, dead bugs, and rotational movements for functional strength.',
                'video_url'        => 'https://www.youtube.com/embed/DHD1-2P94DI',
                'thumbnail_url'    => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=640&q=80',
                'duration_seconds' => 1200,
                'category'         => 'Core',
                'difficulty'       => 'Intermediate',
                'instructor'       => 'Sarah Chen',
                'tags'             => ['core','abs','stability','planks'],
                'muscle_groups'    => ['Core','Abs'],
                'equipment'        => ['Mat'],
                'views'            => 0,
                'likes'            => 0,
                'is_featured'      => false,
            ],
            [
                'title'            => 'Leg Day Destroyer',
                'description'      => 'Push your legs to the limit with squats, lunges, leg press, and Romanian deadlifts. Not for the faint-hearted!',
                'video_url'        => 'https://www.youtube.com/embed/U4s4mEQ5VQU',
                'thumbnail_url'    => 'https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=640&q=80',
                'duration_seconds' => 3600,
                'category'         => 'Strength',
                'difficulty'       => 'Advanced',
                'instructor'       => 'Marcus Bell',
                'tags'             => ['legs','squats','glutes','quads'],
                'muscle_groups'    => ['Quadriceps','Hamstrings','Glutes','Calves'],
                'equipment'        => ['Barbell','Leg Press','Dumbbells'],
                'views'            => 0,
                'likes'            => 0,
                'is_featured'      => false,
            ],
            [
                'title'            => 'Shoulder & Arms Circuit',
                'description'      => 'Complete shoulder and arm workout using supersets and drop sets. Build definition and strength in one session.',
                'video_url'        => 'https://www.youtube.com/embed/q7LBRaBTkko',
                'thumbnail_url'    => 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=640&q=80',
                'duration_seconds' => 2100,
                'category'         => 'Strength',
                'difficulty'       => 'Intermediate',
                'instructor'       => 'Coach Kelvin',
                'tags'             => ['shoulders','arms','circuit','upper-body'],
                'muscle_groups'    => ['Shoulders','Biceps','Triceps'],
                'equipment'        => ['Dumbbells','Cables'],
                'views'            => 0,
                'likes'            => 0,
                'is_featured'      => false,
            ],
            [
                'title'            => 'Pilates for Beginners',
                'description'      => 'Introduction to Pilates focusing on body control, breathing, and core engagement. Gentle yet effective.',
                'video_url'        => 'https://www.youtube.com/embed/K5PI1vU7e-8',
                'thumbnail_url'    => 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=640&q=80',
                'duration_seconds' => 1800,
                'category'         => 'Yoga',
                'difficulty'       => 'Beginner',
                'instructor'       => 'Sarah Chen',
                'tags'             => ['pilates','beginners','core','flexibility'],
                'muscle_groups'    => ['Core','Full Body'],
                'equipment'        => ['Mat'],
                'views'            => 0,
                'likes'            => 0,
                'is_featured'      => false,
            ],
            [
                'title'            => 'Tabata Sprint Intervals',
                'description'      => '20 minutes of pure tabata sprints — 20 seconds max effort, 10 seconds rest. Boost metabolism and burn fat fast.',
                'video_url'        => 'https://www.youtube.com/embed/NIRi5vjLT4w',
                'thumbnail_url'    => 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=640&q=80',
                'duration_seconds' => 1200,
                'category'         => 'HIIT',
                'difficulty'       => 'Advanced',
                'instructor'       => 'Coach Kelvin',
                'tags'             => ['tabata','sprints','cardio','fat-burn'],
                'muscle_groups'    => ['Full Body','Cardio'],
                'equipment'        => ['None'],
                'views'            => 0,
                'likes'            => 0,
                'is_featured'      => false,
            ],
            [
                'title'            => 'Flexibility & Mobility Routine',
                'description'      => 'Improve your range of motion and recover faster with this comprehensive flexibility and mobility session.',
                'video_url'        => 'https://www.youtube.com/embed/g_tea8ZNk5A',
                'thumbnail_url'    => 'https://images.unsplash.com/photo-1549576490-b0b4831ef60a?w=640&q=80',
                'duration_seconds' => 2400,
                'category'         => 'Yoga',
                'difficulty'       => 'Beginner',
                'instructor'       => 'Sarah Chen',
                'tags'             => ['flexibility','mobility','recovery','stretching'],
                'muscle_groups'    => ['Full Body'],
                'equipment'        => ['Mat','Foam Roller'],
                'views'            => 0,
                'likes'            => 0,
                'is_featured'      => false,
            ],
            [
                'title'            => 'Push-Up Progressions',
                'description'      => 'Master the push-up from beginner to advanced. Wall push-ups all the way to archer and one-arm variations.',
                'video_url'        => 'https://www.youtube.com/embed/IODxDxX7oi4',
                'thumbnail_url'    => 'https://images.unsplash.com/photo-1598971639058-fab3c3109a01?w=640&q=80',
                'duration_seconds' => 900,
                'category'         => 'Strength',
                'difficulty'       => 'Beginner',
                'instructor'       => 'Marcus Bell',
                'tags'             => ['push-ups','bodyweight','chest','beginner'],
                'muscle_groups'    => ['Chest','Shoulders','Triceps'],
                'equipment'        => ['None'],
                'views'            => 0,
                'likes'            => 0,
                'is_featured'      => false,
            ],
        ];

        foreach ($videos as $v) {
            Video::create($v);
        }

        $this->command->info('12 videos seeded.');
    }
}
